server:
  error.include-stacktrace: never
  compression:
    enabled: true
  http2:
    enabled: true

management:
  endpoint:
    health:
      show-components: always
      probes:
        enabled: true

  metrics:
    export:
      defaults:
        enabled: true
    web:
      server:
        request:
          autotime:
            enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics